version: '3'

services:
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

###< symfony/mailer ###

  mailhog:
    container_name: programwithgio-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'
    ports: [8025, 1025]

